// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.App.Greet(arg1);
      },
    },
    "Service": {
      /**
       * All
       * @returns {Promise<Array.<Todo>>}  - Go Type: []main.Todo
       */
      "All": () => {
        return window.go.main.Service.All();
      },
    },
  },

};
export default go;
